version: '3.8'
services:
  portfolio:
    image: portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    # networks: ["net", "common"]
    environment:
      - LETSENCRYPT_HOST
      - VIRTUAL_HOST
      - TRUSTED_PROXIES

networks:
  # net:
  #   external: true
  common: